apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
  labels:
    app: publisher
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
    spec:
      containers:
      - name: publisher
        image: publisher:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: PUBSUB_EMULATOR_HOST
          value: "host.docker.internal:8085"
        - name: GCP_PROJECT_ID
          value: "local-project"
---
apiVersion: v1
kind: Service
metadata:
  name: publisher
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: publisher